IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = N'Code_id' AND TABLE_NAME = 'Students')
ALTER TABLE dbo.Students
ADD Code_id INT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = N'Code_id' AND TABLE_NAME = 'Students')
ALTER TABLE dbo.Students
ADD CONSTRAINT FK_Students_Direction_Code_id FOREIGN KEY (Code_id) REFERENCES Direction(Code_id);
